export const ICON_OPTIONS = [
  { value: "shopping-cart", label: "Supermercat" },
  { value: "utensils", label: "Restaurants" },
  { value: "coffee", label: "Cafè" },
  { value: "car", label: "Cotxe" },
  { value: "train", label: "Transport públic" },
  { value: "plane", label: "Avió" },
  { value: "fuel", label: "Gasolina" },
  { value: "home", label: "Llar" },
  { value: "zap", label: "Electricitat" },
  { value: "droplets", label: "Aigua" },
  { value: "wifi", label: "Internet" },
  { value: "heart-pulse", label: "Salut" },
  { value: "pill", label: "Farmàcia" },
  { value: "stethoscope", label: "Metge" },
  { value: "gamepad-2", label: "Videojocs" },
  { value: "music", label: "Música" },
  { value: "film", label: "Cinema" },
  { value: "book", label: "Llibres" },
  { value: "dumbbell", label: "Gimnàs" },
  { value: "banknote", label: "Efectiu" },
  { value: "credit-card", label: "Targeta" },
  { value: "trending-up", label: "Inversions" },
  { value: "piggy-bank", label: "Estalvis" },
  { value: "briefcase", label: "Feina" },
  { value: "gift", label: "Regal" },
  { value: "tag", label: "General" },
  { value: "more-horizontal", label: "Altres" },
  { value: "star", label: "Especial" },
  { value: "shirt", label: "Roba" },
  { value: "graduation-cap", label: "Educació" },
  { value: "smartphone", label: "Tecnologia" },
  { value: "baby", label: "Fills" },
  { value: "paw-print", label: "Mascotes" },
] as const

export type IconValue = typeof ICON_OPTIONS[number]["value"]