import type { LucideIcon } from "lucide-react"
import {
  Baby,
  Banknote,
  Bed,
  Book,
  Briefcase,
  Camera,
  Car,
  Coffee,
  CreditCard,
  Droplets,
  Dumbbell,
  Film,
  Fuel,
  Gamepad2,
  Gift,
  GlassWater,
  GraduationCap,
  HeartPulse,
  Home,
  Map,
  MoreHorizontal,
  Music,
  PartyPopper,
  PawPrint,
  PiggyBank,
  Pill,
  Plane,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Star,
  Stethoscope,
  Tag,
  Ticket,
  Train,
  TrendingUp,
  Utensils,
  Wifi,
  Zap,
} from "lucide-react"

export const iconMap: Record<string, LucideIcon> = {
  baby: Baby,
  banknote: Banknote,
  bed: Bed,
  book: Book,
  briefcase: Briefcase,
  camera: Camera,
  car: Car,
  coffee: Coffee,
  "credit-card": CreditCard,
  droplets: Droplets,
  dumbbell: Dumbbell,
  film: Film,
  fuel: Fuel,
  "gamepad-2": Gamepad2,
  gift: Gift,
  "glass-water": GlassWater,
  "graduation-cap": GraduationCap,
  "heart-pulse": HeartPulse,
  home: Home,
  map: Map,
  "more-horizontal": MoreHorizontal,
  music: Music,
  "party-popper": PartyPopper,
  "paw-print": PawPrint,
  "piggy-bank": PiggyBank,
  pill: Pill,
  plane: Plane,
  shirt: Shirt,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  smartphone: Smartphone,
  star: Star,
  stethoscope: Stethoscope,
  tag: Tag,
  ticket: Ticket,
  train: Train,
  "trending-up": TrendingUp,
  utensils: Utensils,
  wifi: Wifi,
  zap: Zap,
}

export const fallbackIcon = Tag