import type { LucideIcon } from "lucide-react"
import {
  Activity,
  Anchor,
  Baby,
  Banknote,
  Bed,
  Beer,
  Bike,
  Book,
  Box,
  Briefcase,
  Bus,
  Cake,
  Camera,
  Car,
  Coffee,
  Coins,
  CreditCard,
  Droplets,
  Dumbbell,
  Euro,
  Film,
  Fuel,
  Gamepad2,
  Gift,
  GlassWater,
  GraduationCap,
  Hammer,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  Landmark,
  Laptop,
  Map,
  MapPin,
  MoreHorizontal,
  Moon,
  Music,
  PartyPopper,
  PawPrint,
  Phone,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Smile,
  Star,
  Stethoscope,
  Sun,
  Tag,
  Ticket,
  Train,
  TrendingUp,
  Tv,
  Users,
  Utensils,
  Wallet,
  Wifi,
  Wine,
  Wrench,
  Zap,
} from "lucide-react"

export const iconMap: Record<string, LucideIcon> = {
  activity: Activity,
  anchor: Anchor,
  baby: Baby,
  banknote: Banknote,
  bed: Bed,
  beer: Beer,
  bike: Bike,
  book: Book,
  box: Box,
  briefcase: Briefcase,
  bus: Bus,
  cake: Cake,
  camera: Camera,
  car: Car,
  coffee: Coffee,
  coins: Coins,
  "credit-card": CreditCard,
  droplets: Droplets,
  dumbbell: Dumbbell,
  euro: Euro,
  film: Film,
  fuel: Fuel,
  "gamepad-2": Gamepad2,
  gift: Gift,
  "glass-water": GlassWater,
  "graduation-cap": GraduationCap,
  hammer: Hammer,
  headphones: Headphones,
  heart: Heart,
  "heart-pulse": HeartPulse,
  home: Home,
  landmark: Landmark,
  laptop: Laptop,
  map: Map,
  "map-pin": MapPin,
  "more-horizontal": MoreHorizontal,
  moon: Moon,
  music: Music,
  "party-popper": PartyPopper,
  "paw-print": PawPrint,
  phone: Phone,
  "piggy-bank": PiggyBank,
  pill: Pill,
  pizza: Pizza,
  plane: Plane,
  scissors: Scissors,
  shirt: Shirt,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  smartphone: Smartphone,
  smile: Smile,
  star: Star,
  stethoscope: Stethoscope,
  sun: Sun,
  tag: Tag,
  ticket: Ticket,
  train: Train,
  "trending-up": TrendingUp,
  tv: Tv,
  users: Users,
  utensils: Utensils,
  wallet: Wallet,
  wifi: Wifi,
  wine: Wine,
  wrench: Wrench,
  zap: Zap,
}

export const fallbackIcon = Tag